---
abstract: 'a more sensible way to change directories'
author:
  - 'David Golden <dagolden@cpan.org>'
  - 'Michael G. Schwern <schwern@pobox.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.17'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: File-chdir
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  File::chdir:
    file: lib/File/chdir.pm
    version: '0.1009'
  File::chdir::ARRAY:
    file: lib/File/chdir.pm
    version: '0.1009'
  File::chdir::SCALAR:
    file: lib/File/chdir.pm
    version: '0.1009'
requires:
  Carp: '0'
  Cwd: '3.16'
  Exporter: '0'
  File::Spec::Functions: '3.27'
  perl: '5.006'
  strict: '0'
  vars: '0'
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=File-chdir
  homepage: https://github.com/dagolden/File-chdir
  repository: https://github.com/dagolden/File-chdir.git
version: '0.1009'
x_authority: cpan:DAGOLDEN
x_contributors:
  - 'Joel Berger <joel.a.berger@gmail.com>'
